name: Build coe-cli

on:
  workflow_dispatch:
    inputs: {}
  release:
    types: [published]

permissions:
  packages: write

jobs:
  docker_build:
    name: Docker container image build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: '{{defaultContext}}:coe-cli'
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/coe-cli:${{ github.ref_name || github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/coe-cli:latest
